In [1]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
import glob

In [2]:

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
cap = cv.VideoCapture(0)
cap.open

while cap.isOpened():
    ret, frame = cap.read()
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)
    cv.imshow("preview", frame)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        # Draw and display the corners
        cv.drawChessboardCorners(frame, (7,6), corners2, ret)
        cv.imshow("preview", frame)
    if cv.waitKey(1) & 0xFF == ord('q'):
        break
cap.release
cv.destroyAllWindows()

In [3]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
if(ret):
    print(mtx, dist, rvecs, tvecs)

[[450.47198729   0.         306.83766433]
 [  0.         450.56062548 183.45145229]
 [  0.           0.           1.        ]] [[ 0.20086909 -1.19094546  0.00327047 -0.01362785  2.01310632]] [array([[-0.18506135],
       [-0.14531696],
       [-1.4727818 ]]), array([[-0.20818226],
       [-0.0276132 ],
       [ 0.05459912]]), array([[-0.1977868 ],
       [ 0.16272561],
       [ 1.61303901]]), array([[-0.1977868 ],
       [ 0.16272561],
       [ 1.61303901]]), array([[-0.22988186],
       [-0.0311847 ],
       [ 0.04505521]]), array([[-0.25399718],
       [ 0.19303877],
       [ 1.60818411]]), array([[-0.25399718],
       [ 0.19303877],
       [ 1.60818411]]), array([[-1.35885225e-04],
       [-4.29371729e-01],
       [-3.05476495e+00]]), array([[-1.35885225e-04],
       [-4.29371729e-01],
       [-3.05476495e+00]]), array([[-0.14653153],
       [ 0.16483013],
       [ 1.66411805]]), array([[-0.21317896],
       [ 0.03930587],
       [ 0.10330197]]), array([[-0.21317896],
       [ 0.039

In [4]:
print(dist)

[[ 0.20086909 -1.19094546  0.00327047 -0.01362785  2.01310632]]


In [5]:
print(mtx)

[[450.47198729   0.         306.83766433]
 [  0.         450.56062548 183.45145229]
 [  0.           0.           1.        ]]
